feat: set max payment fee ration for LND
BoltzExchange/boltz-backend pull request #299
Opened 2022-10-27 12:36 UTC by yuyaogawa

2022-10-27 16:27 UTC, michael1011 requested changes
One small problem to be fixed, else the PR looks good!

Thank you!

2022-10-27 16:27 UTC, michael1011 commented on lib/lightning/LndClient.ts
> +    LndClient.maxPaymentFeeRatio = maxPaymentFeeRatio > 0 ? maxPaymentFeeRatio: 0.03;
Because the `maxPaymentFeeRatio` is now set from the constructor, it shouldn't be static anymore.

Else the last client initialized sets the value for all of the `LndClient`s.

2022-10-28 00:22 UTC, yuyaogawa commented on lib/lightning/LndClient.ts
> +    LndClient.maxPaymentFeeRatio = maxPaymentFeeRatio > 0 ? maxPaymentFeeRatio: 0.03;
Fixed the `maxPaymentFeeRatio` property.

2022-10-29 13:34 UTC, michael1011 approved these changes

2022-10-29 13:34 UTC, merged