feat: gitbook
BoltzExchange/boltz-backend pull request #369
Opened 2023-07-26 15:03 UTC by armurbalda

2023-07-26 15:41 UTC, michael1011 requested changes
Is there a preview somewhere to have a look at?

2023-07-26 15:41 UTC, michael1011 commented on docs/lifecycle.md
> +5. once the said transaction is included in a block (or found in the mempool in case of [0-confirmation](./)) Boltz will try to pay the invoice provided by the user in order to claim the onchain coin
Why would you rename the 0-conf file to README.md?

2023-07-27 08:11 UTC, armurbalda commented on docs/lifecycle.md
> +5. once the said transaction is included in a block (or found in the mempool in case of [0-confirmation](./)) Boltz will try to pay the invoice provided by the user in order to claim the onchain coin
It was a mistake, not ready for review yet

2023-07-27 08:11 UTC, armurbalda commented
> Is there a preview somewhere to have a look at?

https://boltz.gitbook.io/new-docs/

But NOT ready for review yet

2023-08-04 01:26 UTC, michael1011 requested changes
All the # links in the Markdown files are broken

2023-08-04 01:26 UTC, michael1011 commented on docs/api.md
> +}
Indentation is inconsistent

2023-08-04 01:26 UTC, michael1011 commented on docs/api.md
> +}
Indentation again

2023-08-04 01:26 UTC, michael1011 commented on docs/api.md
> +~~Swaps from account-based EVM chains like RSK do not require a new address for every swap. `/createswap` takes the details of the swap (like lightning invoice and pair) and Boltz waits until the use
Link won't work for sure

2023-08-04 01:26 UTC, michael1011 commented on docs/api.md
> +* `pairId`: the pair of which the swap should be created, for more check [#supported-pairs](api.md#supported-pairs "mention")
```suggestion
* `pairId`: the pair of which the swap should be created, for more check [#supported-pairs](api.md#supported-pairs)
```

2023-08-04 01:26 UTC, michael1011 commented on docs/api.md
> +This endpoint is used to broadcast transactions on UTXO chains. It is similar to [`/gettransaction`](api.md#raw-transactions) but instead of getting the hex representation of existing transactions on
```suggestion
This endpoint is used to broadcast transactions on UTXO chains. It is similar to [`/gettransaction`](api.md#raw-transactions) but instead of getting the hex representation of existing transactions on the chain, this call broadcasts _new_ transactions to the network. It is mainly intended to be used to broadcast claim and refund transactions on user's behalf. It returns the id of the broacasted transaction, which can be used to verify that the refund transaction was broadcasted successfully.
```

Not sure if getting an ID back should be used to check for success. The HTTP status should be used for that. Some HTTP clients, like the JS fetch API resolve or reject based on HTTP status anyways

2023-08-04 01:26 UTC, michael1011 commented on docs/api.md
> +## Authentication
How about putting authentication and the one authenticated endpoint we have at the very bottom?

2023-08-04 01:26 UTC, michael1011 commented on docs/channel-creation.md
> +###
?

2023-08-04 01:26 UTC, michael1011 commented on docs/channel-creation.md
> +One way is to incorporate a logic similar to the one of the external daemon described below directly into the Lightning implementation. This can be done by modifying the source code of the client or
```suggestion
One way is to incorporate a logic similar to the one of the external daemon described below directly into the Lightning implementation. This can be done by modifying the source code of the client or by creating a plugin. We provide a [Core Lightning](https://github.com/ElementsProject/lightning) plugin for this use case. The full source code of the plugin can be found in [this repository](https://github.com/BoltzExchange/channel-creation-plugin).
```

2023-08-04 01:26 UTC, michael1011 commented on docs/deployment.md
> +* The latest [node.js lts and npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) installed. We recommend using [nvm](https://github.com/nvm-sh/nvm#install--update-script) to mana
```suggestion
* The latest [Node.js LTS and npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) installed. We recommend using [nvm](https://github.com/nvm-sh/nvm#install--update-script) to manage npm installs: `nvm install --lts`
```

2023-08-04 01:26 UTC, michael1011 commented on docs/deployment.md
> +Boltz Backend requires a synced Bitcoin Core Instance to connect to the Bitcoin mainchain. Similarly Elements Core to connect to the Liquid sidechain etc. Bitcoin Core must
```suggestion
Boltz Backend requires a synced Bitcoin Core Instance to connect to the Bitcoin mainchain. Similarly, Elements Core to connect to the Liquid sidechain etc. Bitcoin Core must:
```

2023-08-04 01:26 UTC, michael1011 commented on docs/regtest.md
> +* The latest [node.js lts and npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) installed. We recommend using [nvm](https://github.com/nvm-sh/nvm#install--update-script) to mana
```suggestion
* The latest [Node.js LTS and npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) installed. We recommend using [nvm](https://github.com/nvm-sh/nvm#install--update-script) to manage npm installs: `nvm install --lts`
```

2023-08-04 01:26 UTC, michael1011 commented on docs/deployment.md
> +quote = "BTC"
```suggestion
base = "L-BTC"
quote = "BTC"
```

2023-08-04 01:26 UTC, michael1011 commented on docs/scripting.md
> +Examples for generating all of these addresses with `Node.js` can be found in the [`boltz-core` r](https://github.com/BoltzExchange/boltz-core/blob/master/lib/swap/Scripts.ts)eference library.
```suggestion
Examples for generating all of these addresses with `Node.js` can be found in the [`boltz-core`](https://github.com/BoltzExchange/boltz-core/blob/master/lib/swap/Scripts.ts) reference library.
```

2023-08-04 01:26 UTC, michael1011 commented on docs/scripting.md
> +Examples for all three output types can be found in the [`boltz-core` ](https://github.com/BoltzExchange/boltz-core/blob/master/lib/swap/Claim.ts#L23)[r](https://github.com/BoltzExchange/boltz-core/b
```suggestion
Examples for all three output types can be found in the [`boltz-core` ](https://github.com/BoltzExchange/boltz-core/blob/master/lib/swap/Claim.ts#L23) [reference library](https://github.com/BoltzExchange/boltz-core/blob/master/lib/swap/Scripts.ts).
```

2023-09-13 15:06 UTC, kilrau commented
> All the # links in the Markdown files are broken

On gitbook they work, that's the important thing. Try it out: https://boltz.gitbook.io/new-docs/v/boltz-backend-1/

2023-09-13 15:28 UTC, kilrau commented on docs/README (1).md
> +---
Indeed not, fixed in https://github.com/BoltzExchange/boltz-backend/pull/369/commits/e4e5f7cf048da4d700bd074ff6b5a6283484b2ba

2023-09-13 16:19 UTC, kilrau commented on docs/README.md
> +In the following section we'll walk through existing swap types & states and then describe the REST API in the next section.
True, changed wording re that

2023-09-13 16:20 UTC, kilrau commented on docs/README.md
> +> [`https://api.boltz.exchange/version`](https://api.boltz.exchange/version)
Changed wording slightly but I'd really want to keep it, it's just such a reassuring effect to click on the link and see "API works"

2023-09-13 17:04 UTC, kilrau commented on docs/api.md
> +### Backend Version
Ayt. Fixed in https://github.com/BoltzExchange/boltz-backend/pull/369/commits/8323a7db65d8d11f9d8e51d2bade595cd4c3f7db

2023-09-13 18:27 UTC, kilrau commented on docs/README.md
> +  supported pairs as well as to create and monitor swaps.
Changed `api.md` description in https://github.com/BoltzExchange/boltz-backend/pull/369/commits/f80bc3ae76a0633997b1dad756bb0c242dc206fd

2023-09-13 19:25 UTC, kilrau commented on docs/scripting.md
> +Examples for generating all of these addresses with `Node.js` can be found in the [`boltz-core` r](https://github.com/BoltzExchange/boltz-core/blob/master/lib/swap/Scripts.ts)eference library.
Nice catch

2023-09-19 16:34 UTC, kilrau approved these changes

2023-10-03 13:13 UTC, merged