docs: evm & misc updates
BoltzExchange/boltz-backend pull request #429
Opened 2023-11-03 10:31 UTC by kilrau

Preview: https://boltz.gitbook.io/dev-api-boltz-backend/

2023-11-21 09:07 UTC, maybeast reviewed
- new links seem to be be working/valid
- still waiting for RSK mainnet contract address before merging
- might consider removing channel opening swaps docs all together if they're currently disabled

2023-11-21 09:07 UTC, maybeast commented on docs/README.md
> +  supported pairs and to create & monitor swaps.
minor nit: feels weird to use & + "and" in the same sentence as it's not consistent

2023-11-21 09:26 UTC, kilrau commented
+ still need to add more details on which values are needed for evm refunds and best also an rpc call example for the emergency procedure how to obtain them via contract logs if refund info was lost

2023-11-30 21:17 UTC, michael1011 requested changes
>  Remove channel creation info? Don't think channel creations will be coming back anything similar to the current implementation. We should remove them from API too. Wdyt? 

Let's remove them

>  Add to "Don't trust verify" EVM section: verify that swap contract is the legit swap contract by comparing bytecode of swap contract is == bytecontract (link boltz-core source)

That's not in boltz-core and going in there. Heavily depends on what Ethereum library you are using

2023-11-30 21:17 UTC, michael1011 commented on docs/claiming-swaps.md
> +Claiming works a little different for every output type, but you always need the preimage, private key and original redeem script. Hence, Boltz API clients need to ensure a safe way to store these va
We always use the witness script.

2023-11-30 21:17 UTC, michael1011 commented on docs/claiming-swaps.md
> +Examples for all output types can be found in the [`boltz-core` ](https://github.com/BoltzExchange/boltz-core/blob/master/lib/swap/Claim.ts#L23)reference library.
```suggestion
Examples for all output types can be found in the [`boltz-core`](https://github.com/BoltzExchange/boltz-core/blob/master/lib/swap/Claim.ts#L23) reference library.
```

2023-11-30 21:17 UTC, michael1011 commented on docs/claiming-swaps.md
> +The HTLCs that Boltz uses on EVM chains are not single use scripts, but contracts. The contract takes care of claiming funds to the specified `claimAddress`, a separate claim transaction is not neces
Sending to the `claimAddress` is the separate claim transaction

2023-11-30 21:17 UTC, michael1011 commented on docs/claiming-swaps.md
> +The HTLCs that Boltz uses on EVM chains are not single use scripts, but contracts. The contract takes care of claiming funds to the specified `claimAddress`, a separate claim transaction is not neces
That is not the reference. But the contracts

2023-11-30 21:17 UTC, michael1011 commented on docs/claiming-swaps.md
> +The HTLCs that Boltz uses on EVM chains are not single use scripts, but contracts. In order to submit a refund, one calls the `refund` function of the contract. Similar to UTXO chains, Boltz API clie
Not the reference

2023-11-30 21:17 UTC, michael1011 commented on docs/dont-trust.-verify.md
> +Boltz API returns a redeem script and a derived chain address when creating swaps. After verifying that the redeem script is valid (checking preimage hash, public key, timeout block height of the HTL
Maybe link to the script generation functions in boltz-core

2023-11-30 21:17 UTC, michael1011 commented on docs/dont-trust.-verify.md
> +<hash of the P2WSH output script>
```suggestion
<RIPEMD-160 hash of the P2WSH output script>
```

2023-11-30 21:17 UTC, michael1011 commented on docs/dont-trust.-verify.md
> +#### P2WSH
Tbh it would be cleaner that start with that one, because the nested Segwit one depends on its result

2023-11-30 21:25 UTC, kilrau commented on docs/lifecycle.md
> +Normal Submarine Swaps move bitcoin from the **chain to Lightning**. "Chain" can be the Bitcoin mainchain or, for instance, the Liquid sidechain. Typically, the user creates a Lightning invoice for B
Not controlled by us nor user for the swap duration. We had this question quite often "it's locked in a Boltz address".

2023-12-15 15:58 UTC, kilrau commented
> > Remove channel creation info? Don't think channel creations will be coming back anything similar to the current implementation. We should remove them from API too. Wdyt?
> 
> Let's remove them

Done.

> > Add to "Don't trust verify" EVM section: verify that swap contract is the legit swap contract by comparing bytecode of swap contract is == bytecontract (link boltz-core source)
> 
> That's not in boltz-core and going in there. Heavily depends on what Ethereum library you are using

Generalized. We'll add details like the source of the bytecode, example code how to do it later.

2023-12-15 16:09 UTC, kilrau commented on docs/api.md
> +    * `minerFees`: The network fees charged for locking up and claiming funds onchain. These values are absolute, denominated in **10 \*\* -8** of the quote asset, and are based on estimations from p
rmed

2023-12-15 16:11 UTC, kilrau commented on docs/api.md
> +* `orderSide`: Possible values are `buy` & `sell`. Currently the only valid option is `sell` across all pairs of swap type `submarine`. The value `buy` for normal swaps of e.g. the `L-BTC/BTC` pair s
Explain.

2023-12-19 13:04 UTC, kilrau commented on docs/api.md
> +* `orderSide`: Possible values are `buy` & `sell`. Currently the only valid option is `sell` across all pairs of swap type `submarine`. The value `buy` for normal swaps of e.g. the `L-BTC/BTC` pair s
Ok you are right in the case of BTC/BTC both `buy` and `sell` work and lead to the exact same thing. Still I'd "recommend" using `sell` across all pairs for consistency, removed the "not valid" expression. Can't wait for apiv2 to get rid of this.

2023-12-19 13:20 UTC, kilrau commented on docs/api.md
> +* `orderSide`: Possible values are `buy` & `sell`. Currently the only valid option is `sell` across all pairs of swap type `submarine`. The value `buy` for normal swaps of e.g. the `L-BTC/BTC` pair s
Fixed.

2023-12-19 13:21 UTC, kilrau commented on docs/api.md
> +* `referral`: Partner referral ID&#x20;
fixed

2023-12-19 13:36 UTC, kilrau commented on docs/api.md
> +* `address`: Address in which the bitcoin will be locked up. For UTXO chains, this is a SegWit `P2SHP2WSH` (`P2WSH` nested in a `P2SH`) for the sake of compatibility and for EVM chains like RSK this
True, thanks! Fixed.

2023-12-19 13:39 UTC, kilrau commented on docs/api.md
> +In case the amount to be swapped is not known when creating a Normal Submarine Swap, the invoice can be set afterwards; even if the chain bitcoin were sent already. In this case, you want to first us
bitcoin the asset not capitalized, Bitcoin the technology/chain capitalized

2023-12-19 13:45 UTC, kilrau commented on docs/api.md
> +      "chainId": 31
Imo it's clear that the *values* of the responses shown in our docs are not up-to-date because that's simply not possible. take e.g. `GET /getfeeestimation` or any transaction id, redeem script etc. The same is valid for way chain id's or contract addresses change - the API calls exist to get up-to-date values otherwise we could just point everyone to the docs. Possible parameters have to be kept up to date, but values are always samples.

2023-12-19 13:47 UTC, kilrau commented on docs/api.md
> +* `orderSide`: Possible values are `buy` & `sell`. Currently the only valid option is `buy` across all pairs of swap type `reversesubmarine`. The value `sell` for reverse swaps of e.g. the `L-BTC/BTC
Fixed.

2023-12-19 14:03 UTC, kilrau commented on docs/claiming-swaps.md
> +Claiming works a little different for every output type, but you always need the preimage, private key and original redeem script. Hence, Boltz API clients need to ensure a safe way to store these va
rmed "signature script"

2023-12-19 14:25 UTC, kilrau commented on docs/claiming-swaps.md
> +The HTLCs that Boltz uses on EVM chains are not single use scripts, but contracts. The contract takes care of claiming funds to the specified `claimAddress`, a separate claim transaction is not neces
Hope "The source of the contracts can be found here." sounds better to you. I think we should say "source" since the contracts itself live on the chain.

2023-12-19 14:36 UTC, kilrau commented on docs/dont-trust.-verify.md
> +#### P2WSH
Like this? Also changed to `<RIPEMD-160 hash of the SHA256 hash of the P2WSH output script>` to be more precise. Please carefully check @michael1011

2023-12-19 14:37 UTC, kilrau commented on docs/dont-trust.-verify.md
> +Boltz API Clients should verify that EVM swaps are carried out using the latest contract addresses found here. <mark style="color:orange;">TODO: when deployed, link latest rsk mainnet contract addres
Fixed. It's a generic sentence but for now good enough to serve as a reminder.

2023-12-19 14:40 UTC, kilrau commented on docs/lifecycle.md
> +If the user successfully set up the Lightning payment and Boltz successfully locked up bitcoin on the chain, but the Boltz API Client did not claim the locked chain bitcoin until swap expiry, Boltz w
Was intentional, but I get you want wording to be in line with swap state wording. Did `claimed back by` -> `refunded back to`.

2023-12-19 14:54 UTC, kilrau commented on docs/lifecycle.md
> +If the user successfully set up the Lightning payment and Boltz successfully locked up bitcoin on the chain, but the Boltz API Client did not claim the locked chain bitcoin until swap expiry, Boltz w
Removed the entire last section, it's not useful info and only confusing. The swap invoice already had a pending lightning payment to get the swap into this state in the first palce so not sure why we were talking about "paying the invoice" after boltz refunded itself. It's not possible period.

2023-12-19 14:59 UTC, kilrau commented on docs/claiming-swaps.md
> +The HTLCs that Boltz uses on EVM chains are not single use scripts, but contracts. The contract takes care of claiming funds to the specified `claimAddress`, a separate claim transaction is not neces
Removed the entire sentence since it's false and everything works the same way as on UTXO chains, first lockup tx, then separate claim tx, so no need to say anything.

2023-12-19 15:24 UTC, kilrau commented on docs/dont-trust.-verify.md
> +Boltz API returns a redeem script and a derived chain address when creating swaps. After verifying that the redeem script is valid (checking preimage hash, public key, timeout block height of the HTL
Did that, also to web-app as example. Please double check.

2024-01-08 16:00 UTC, michael1011 approved these changes

2024-01-08 16:18 UTC, merged