fix: API v2, wording, style
BoltzExchange/boltz-backend pull request #486
Opened 2024-02-15 15:23 UTC by kilrau

Preview: https://boltz.gitbook.io/boltz-backend-dev

2024-02-15 23:26 UTC, michael1011 requested changes

2024-02-15 23:26 UTC, michael1011 commented on docs/0-conf.md
> +_0-conf Swaps are subject to network conditions and generally only available on UTXO chains like Bitcoin or Liquid._
```suggestion
_0-conf Swaps are subject to network conditions and only available on UTXO chains like Bitcoin or Liquid._
```

EVM txs are always fully replaceable

2024-02-15 23:26 UTC, michael1011 commented on docs/lifecycle.md
> +6. `transaction.claim.pending`: This status indicates that Boltz is ready for the creation of a cooperative signature for a keypath spend. Taproot Swaps are not claimed immediately by Boltz after the
```suggestion
6. `transaction.claim.pending`: This status indicates that Boltz is ready for the creation of a cooperative signature for a keypath spend. Taproot Swaps are not claimed immediately by Boltz after the invoice has been paid, but instead Boltz waits for the API client to post a signature for a key path spend. If the API client does not cooperate in a key path spend, Boltz will eventually claim via the script path.
```

The reason is not really relevant for the status and the batching is also not important to the client

2024-02-15 23:26 UTC, michael1011 commented on docs/claiming-swaps.md
> +* **refund transactions** to claim refunds for chain bitcoin locked in failed **Submarine Swaps**
Not a fan of the "claim refund" terminology. Kinda confusing to use the word "claim" for refunds

2024-02-15 23:26 UTC, michael1011 commented on docs/claiming-swaps.md
> +Key path spends should be preferred over script path spends. One reason is the smaller chain footprint and thus cheaper miner fees and another reason is because key path spends are better for privacy
```suggestion
Key path spends should be preferred over script path spends. One reason is the smaller chain footprint and thus cheaper miner fees and another reason is because key path spends are better for privacy as they don't reveal anything about the atomic swap on the chain.
```

2024-02-15 23:26 UTC, michael1011 commented on docs/claiming-swaps.md
> +Partial signatures from Boltz use `SIGHASH_DEFAULT`.
That's also relevant for refunds

2024-02-18 15:31 UTC, kilrau commented on docs/claiming-swaps.md
> +* **refund transactions** to claim refunds for chain bitcoin locked in failed **Submarine Swaps**
We had this topic before. We'll keep it for now.

2024-02-18 15:37 UTC, kilrau commented on docs/claiming-swaps.md
> +Partial signatures from Boltz use `SIGHASH_DEFAULT`.
Moved into Taproot section

2024-02-18 15:47 UTC, merged