feat: add setswapstatus to boltz-cli
BoltzExchange/boltz-backend pull request #500
Opened 2024-03-08 09:44 UTC by maybeast

This commit adds a new `boltz-cli setswapstatus <swapID> <status>` command to update swap statuses manually.

Closes #495

2024-03-08 12:09 UTC, michael1011 requested changes

2024-03-08 12:09 UTC, michael1011 commented on lib/service/Service.ts
> +    await SwapRepository.setSwapStatus(swap, status);
1) does not handle reverse swaps
2) just updating the status in the database does not update the cache in `Controller.ts`

Having that cache in there and the way it is updated is not optimal, might want to consider a refactor to be able to update the cached status properly via gRPC

2024-03-11 09:32 UTC, maybeast commented
Updated. As discussed internally we're only going to handle 2 statuses, `invoice.pending` and `invoice.failedToPay`, within the scope of this PR until we refactor the swap update event handling.

2024-03-11 16:12 UTC, michael1011 requested changes
Works! Just some minor feedback on wording and code style

2024-03-11 16:12 UTC, michael1011 commented on test/unit/service/Service.spec.ts
> +      }
`await expect(<promise>).rejects.toEqual()`
Is nicer syntax

2024-03-11 16:12 UTC, michael1011 commented on lib/service/Service.ts
> +export const cancelledViaCliFailureReason = 'canceled via CLI';
That reason is shown directly to the user. Not sure if we want to show `via CLI`. How about `payment has been cancelled`?

2024-03-11 21:17 UTC, michael1011 approved these changes

2024-03-11 21:18 UTC, merged