Chain swap docs
BoltzExchange/boltz-backend pull request #602
Opened 2024-07-10 14:10 UTC by michael1011

2024-07-10 14:39 UTC, kilrau commented
Preview: https://boltz.gitbook.io/api-boltz-backend, please push to branch `gitbook-do-not-delete` to see changes in this preview link

2024-07-11 11:05 UTC, kilrau commented
Gitbook tabs looking good now

![image](https://github.com/BoltzExchange/boltz-backend/assets/19181985/d6520ae4-0145-4483-9e4a-769c346176cc)
![image](https://github.com/BoltzExchange/boltz-backend/assets/19181985/680fcf01-f9e6-4c3d-a27d-0a7e323b1e1d)

2024-07-11 11:56 UTC, kilrau commented
Addresses first point of https://github.com/BoltzExchange/boltz-backend/issues/594

2024-07-12 14:02 UTC, kilrau requested changes

2024-07-12 14:02 UTC, kilrau commented on docs/lifecycle.md
> +All Chain Swaps are Taproot based, so instead claiming by revealing scripts and secrets onchain, a key path spend can be
```suggestion
All Chain Swaps are Taproot-based, so instead of claiming by revealing scripts and secrets onchain, a key path spend can be
```

2024-07-12 14:02 UTC, kilrau commented on docs/lifecycle.md
> +More details about that can be found in the [Claiming Swaps & Refunds](claiming-swaps.md) section.
```suggestion
More details about this can be found in the [Claiming Swaps & Refunds](claiming-swaps.md) section.
```

2024-07-12 14:02 UTC, kilrau commented on docs/lifecycle.md
> +In case the swap was created but the client did not lock any coins, the status will be `swap.expired`.
```suggestion
In case the swap was created, but the client did not lock any coins, the status will be `swap.expired`.
```

2024-07-12 14:02 UTC, kilrau commented on docs/lifecycle.md
> +When the client fails to lock coins in a way that is satisfactory to the server,
```suggestion
When the client fails to lock coins in a way that is satisfactory to the server (e.g. too little),
```

2024-07-12 15:56 UTC, michael1011 commented on docs/api-v2.md
> +const endpoint = 'http://127.0.0.1:9001';
Because doing your first test on mainnet is not a good idea. To use testnet you need more adjustments that just an URL and that testnet endpoint is in the docs already

2024-07-12 16:11 UTC, merged