fix: update description of how preimages are revealed with taproot swaps
BoltzExchange/boltz-backend pull request #639
Opened 2024-08-07 15:58 UTC by kilrau

Preview: https://boltz.gitbook.io/api-boltz-backend-dev

cc @bordalix

2024-08-07 16:05 UTC, bordalix approved these changes

2024-08-07 16:05 UTC, bordalix commented on docs/lifecycle.md
> +   broadcast the claim transaction.
```suggestion
   broadcasts the claim transaction.
```

2024-08-07 20:48 UTC, michael1011 requested changes

2024-08-07 20:48 UTC, michael1011 commented on docs/dont-trust-verify.md
> +successfully claim refunds.
```suggestion
enforce claim and refund transactions.
```

2024-08-07 20:48 UTC, michael1011 commented on docs/dont-trust-verify.md
> +`expectedAmount` in Boltz API responses matches the locally calculated amount.
```suggestion
`expectedAmount` in the API responses matches the locally calculated amount.
```

2024-08-07 20:48 UTC, michael1011 commented on docs/lifecycle.md
> +invoked the API call to construct the claim transaction and supplied the
The client constructs; the API just creates a partial signature for it

2024-08-08 08:53 UTC, kilrau commented on docs/claiming-swaps.md
> +  and **Chain Swaps**.
Went throught all docs and applied the rule `&` in titles only, in-text `and` only

2024-08-08 11:23 UTC, merged