feat: mempool rescan
BoltzExchange/boltz-backend pull request #688
Opened 2024-10-10 23:02 UTC by michael1011

Todos:
- [ ] fetching relevant inputs and outputs for the mempool rescan from database
- [ ] tests

2024-10-16 15:33 UTC, maybeast approved these changes

2024-10-16 15:39 UTC, maybeast requested changes
giving it another look

2024-10-17 07:26 UTC, maybeast requested changes

2024-10-17 07:26 UTC, maybeast commented on boltzr/src/swap/filters.rs
> +    let pending_swaps = swap_repo.get_all(Box::new(
Consider breaking this function down to something like `process_pending_swaps`, `process_pending_reverse_swaps` and `process_pending_chain_swaps`

2024-10-17 11:14 UTC, michael1011 commented on boltzr/src/chain/utils.rs
> +                .filter(|o| !o.script_pubkey.is_empty())
In Elements an empty script is used for the explicit fee output; in Bitcoin empty scripts are not allowed

2024-10-17 11:15 UTC, michael1011 commented on boltzr/src/db/helpers/swap.rs
> +    fn get_all(&self, condition: BoxedCondition<swaps::dsl::swaps>) -> QueryResponse<Vec<Swap>>;
`::table` and `sdsl::swaps` are aliases

2024-10-17 20:01 UTC, maybeast approved these changes

2024-10-17 20:28 UTC, merged